# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 22:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='categoria',
            field=models.ForeignKey(default=datetime.datetime(2016, 2, 21, 22, 17, 4, 785208, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='app.Categoria'),
            preserve_default=False,
        ),
    ]
